# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference 
version: 2.1
jobs:
  build-frontend:
    docker: 
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: cd frontend/ && flutter build apk --debug
      - persist_to_workspace:
          root: frontend
          paths:
            - build/app/outputs/flutter-apk/*
          
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            ls
            ls tmp/workspace
            ls frontend/build/app/outputs/flutter-apk
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -delete $CIRCLE_TAG tmp/workspace

  test-frontend:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: cd frontend/ && flutter test

workflows:
  build-test-deploy:
    jobs:
      - build-frontend:
          filters:
            tags:
              only: /.*/
      - test-frontend:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build-frontend
            - test-frontend
          filters:
            tags:
              only: /^v*.*.*/
            branches:
              ignore: /.*/